# -*- coding: utf-8 -*-
from . import module_branche
from . import res_config_setting
from . import account_analytic_line
from . import contract_cadre
from . import res_partner
from . import project_carnet
from . import project_task
from . import service_type
from . import product_template
from . import sale_subscription
from . import sale_order
from . import account_move
from . import crm_lead
from . import helpdesk_ticket
from . import module_tag
from . import odoo_version
from . import project_database
from . import project_module
from . import project_ressource
from . import ressource_type
from . import kzm_backup_tracker_line
from . import affectation_ressource
from . import affectation_module
# from . import task_request
from . import derogation_task_sold
from . import logger_failed_mail
from . import fechmail_failed_creation
from . import custom_project_tags
